// Auto-generated by OpenLane
module clk_int_div(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_i,
  input rst_ni,
  input en_i,
  input test_mode_en_i,
  input[7:0] div_i,
  input div_valid_i,
  output div_ready_o,
  output clk_o,
  output[7:0] cycl_count_o
);
endmodule
